name: Release version

on:
  push:
    tags:
      - '*'
    #branches: ["master"]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      cwd: LogicScript.VSCode

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install NPM dependencies
      run: npm install
      working-directory: ${{env.cwd}}
      
    - name: Package VSIX
      run: npm run package
      working-directory: ${{env.cwd}}
      
    - name: Publish extension
      run: npm run publish
      working-directory: ${{env.cwd}}
      env:
        VSCE_PAT: ${{secrets.VSCE_PAT}}
      
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{env.cwd}}/vsix/*.vsix
        token: ${{secrets.GH_TOKEN}}
        draft: true
